services:
  app:
    container_name: react_app_prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
# Command for running
# The -f flag stands for file - it lets you specify which compose file to use.
# docker compose -f docker-compose.prod.yml up -d --build
